from app.schemas.application import Application

DUMMY_APPLICATIONS = [
    Application(
        id="app_vsc_1",
        name="Visual Studio Code",
        version="1.85.1",
        category="Development",
        description="Code editor redefined and optimized for building and debugging modern web and cloud applications.",
        package_name="code_1.85.1_amd64.deb",
        installer_type="apt",
        install_command="apt-get install code",
        minimum_battery_percentage=30,
        retry_limit=3,
        auto_remediation=True,
        email_notification=True,
        status="ACTIVE"
    ),
    Application(
        id="app_chrome_1",
        name="Google Chrome",
        version="120.0.0.0",
        category="Browsers",
        description="A fast, secure, and free web browser built for the modern web.",
        package_name="google-chrome-stable_current_amd64.deb",
        installer_type="apt",
        install_command="apt-get install google-chrome-stable",
        minimum_battery_percentage=20,
        retry_limit=3,
        auto_remediation=True,
        email_notification=False,
        status="ACTIVE"
    ),
    Application(
        id="app_docker_1",
        name="Docker Desktop",
        version="4.26.1",
        category="Development",
        description="Collaborative app development platform for developers to build, share, and run applications.",
        package_name="docker-desktop-4.26.1-amd64.deb",
        installer_type="deb",
        install_command="dpkg -i docker-desktop.deb",
        minimum_battery_percentage=50,
        retry_limit=3,
        auto_remediation=True,
        email_notification=True,
        status="ACTIVE"
    ),
    Application(
        id="app_git_1",
        name="Git",
        version="2.43.0",
        category="Utilities",
        description="Fast, scalable, distributed revision control system.",
        package_name="git_2.43.0_amd64.deb",
        installer_type="apt",
        install_command="apt-get install git",
        minimum_battery_percentage=10,
        retry_limit=2,
        auto_remediation=True,
        email_notification=False,
        status="ACTIVE"
    ),
    Application(
        id="app_python_1",
        name="Python",
        version="3.12.1",
        category="Development",
        description="High-level, general-purpose programming language.",
        package_name="python_3.12.1_amd64.deb",
        installer_type="apt",
        install_command="apt-get install python3.12",
        minimum_battery_percentage=20,
        retry_limit=3,
        auto_remediation=True,
        email_notification=True,
        status="ACTIVE"
    ),
    Application(
        id="app_node_1",
        name="Node.js",
        version="20.10.0",
        category="Development",
        description="JavaScript runtime built on Chrome's V8 JavaScript engine.",
        package_name="node-v20.10.0-linux-x64.tar.xz",
        installer_type="apt",
        install_command="apt-get install nodejs",
        minimum_battery_percentage=20,
        retry_limit=3,
        auto_remediation=True,
        email_notification=False,
        status="ACTIVE"
    ),
    Application(
        id="app_postman_1",
        name="Postman",
        version="10.21.0",
        category="Utilities",
        description="API platform for building and using APIs.",
        package_name="postman-10.21.0-linux-x64.tar.gz",
        installer_type="snap",
        install_command="snap install postman",
        minimum_battery_percentage=30,
        retry_limit=3,
        auto_remediation=True,
        email_notification=True,
        status="ACTIVE"
    ),
    Application(
        id="app_intellij_1",
        name="IntelliJ IDEA",
        version="2023.3",
        category="Development",
        description="Capable and Ergonomic Java IDE for Enterprise Java, Scala, Kotlin and much more.",
        package_name="ideaIC-2023.3.tar.gz",
        installer_type="snap",
        install_command="snap install intellij-idea-community --classic",
        minimum_battery_percentage=50,
        retry_limit=3,
        auto_remediation=True,
        email_notification=True,
        status="ACTIVE"
    )
]
